### ISSUE TITLE
Handle keyboard interrupt more nicely

### ISSUE THREAD

**Issue by rezib** [edf-hpc/clara#56]
Currently, Clara gives a backtrace when impatient user hit <ctrl+c>:

```
# clara repo sync whatever
<ctrl+c>
Traceback (most recent call last):
  File "/usr/bin/clara", line 118, in <module>
    m.main()
  File "/usr/lib/python2.7/dist-packages/clara/plugins/clara_repo.py", line 248, in main
    do_sync(dargs['<dist>'], dargs['<suites>'])
  File "/usr/lib/python2.7/dist-packages/clara/plugins/clara_repo.py", line 201, in do_sync
    mirror_root + "/" + s])
  File "/usr/lib/python2.7/dist-packages/clara/utils.py", line 72, in run
    retcode = subprocess.call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 493, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1301, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 478, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

It would be nicer if clara would handle it more kindly :)

Suggestion:
- on 1st hit, tell the user 'yeah I will stop once the sub-command ends but hit me a second time to stop this brutally'
- on 2nd hit, destroy everything.

**Comment by ana** [comment]
Note to self: maybe atexit can handle this.

**Comment by rezib** [comment]
ClusterShell clush command basically implements my suggestion, you may eventually have a look to its source code as an inspiration:
https://github.com/cea-hpc/clustershell/blob/master/lib/ClusterShell/CLI/Clush.py

A short pseudo-code version would be this:
```
warn_flag = False

while not exit_flag:
  try:
    wait_command_end()
  except KeyboardInterrupt:
    if warn_flag:
      exit_flag = True
    else:
      print_warn()
      warn_flag = True
```

But that's just a suggestion, I guess there are many (and probably better) other ways to implement this.
