### ISSUE TITLE
stacktrace when calling logging.debug if failure to connect to conman

### ISSUE THREAD

**Issue by hmlth** [edf-hpc/clara#66]
I know there is an error, but I don't know which one.

~~~
# clara -d ipmi connect thcn01
clara - DEBUG - ['/usr/bin/clara', 'ipmi', 'connect', 'thcn01']
clara - ERROR - Value 'parallel' not found in the section 'ipmi'
clara - WARNING - parallel hasn't been set in config.ini, using 1 as value
Traceback (most recent call last):
  File "/usr/bin/clara", line 118, in <module>
    m.main()
  File "/usr/lib/python2.7/dist-packages/clara/plugins/clara_ipmi.py", line 259, in main
    do_connect(dargs['<host>'], dargs['-j'], dargs['-f'])
  File "/usr/lib/python2.7/dist-packages/clara/plugins/clara_ipmi.py", line 208, in do_connect
    logging.debug("Conman not running. Message on connect: {0}" % e)
TypeError: not all arguments converted during string formatting
~~~

**Comment by ana** [comment]
Fixed at:
https://github.com/edf-hpc/clara/commit/42fef93920b0439bc97459361443dca840d3f635
